export default {
        header:{
                Progress:"Progress",
                Notes:"Notes",
                Reminders:"Reminders",
                Settings:"Settings",
                Frequency:"Notifications",
                PeriodicThoughts:"Periodic thoughts?"
        },
        general:{
                WhereIsYourTongue:"Where is your tongue?",
                KeepUpTheGoodWork:"Keep up the good work!",
                RightThisInstant:"Right this instant, record where you tongue is placed. This will help you track your progress over time.",
                MyTongueWasOnRoof:"My tongue was stuck to the roof of my mouth",
                MyTongueWasPushingTeeth:"I don't know or my tongue was pushing my teeth",
                ComingOutOfMeeting:"Coming out of meeting or a class? Record your thoughts",
                description:{
                        notificationEnabled:"A notification will be sent",
                        reminder:"We'll send you a notification to remind you about it!",
                        tellUsWhatQuietTime:"Tell us what time we should not bother you with notifications.",
                },
                label:{
                        clearProgress:"Clear your data",
                        darkTheme:"Dark Theme",
                        RemindMe:"Remind me",
                        SetQuietPeriod:"Do you want to set a quiet period?",
                        every1Minutes:"Every 1 minute",
                        every2Minutes:"Every 2 minutes",
                        every15Minutes:"Every 15 minutes",
                        every30Minutes:"Every 30 minutes",
                        everyHour:"Every hour",
                        every2Hours:"Every 2 hours",
                        every4Hours:"Every 4 hours",
                        every6Hours:"Every 6 hours",
                        every12Hours:"Every 12 hours",
                        daily:"Daily",
                        weekly:"Weekly",
                        monthly:"Monthly"
                }
        },
        notification:{
            title: "Your tongue!",
            body: "Have you been keeping your tongue on the roof of your mouth?",
        },
        buttons:{
                delete:"Delete",
                confirm:"Confirm",
                cancel:"Cancel",
                IHaveThoughtAboutIt:"I have thought about it",
                TongueWasPushingMyTeeth:"My tongue was pushing my teeth",
        },
        singleWord:{
                times:"times",
        },
        time:{
                "12am":"12am",
                "1am":"1am",
                "2am":"2am",
                "3am":"3am",
                "4am":"4am",
                "5am":"5am",
                "6am":"6am",
                "7am":"7am",
                "8am":"8am",
                "9am":"9am",
                "10am":"10am",
                "11am":"11am",
                "12pm":"12pm",
                "1pm":"1pm",
                "2pm":"2pm",
                "3pm":"3pm",
                "4pm":"4pm",
                "5pm":"5pm",
                "6pm":"6pm",
                "7pm":"7pm",
                "8pm":"8pm",
                "9pm":"9pm",
                "10pm":"10pm",
                "11pm":"11pm",
        }
} as const
