export default {
        header:{
                Progress:"Progrès",
                Notes:"Notes",
                Reminders:"Rappels",
                Settings:"Paramètres",
                Frequency:"Notifications",
                PeriodicThoughts:"Pensées Périodiques",
        },
        general:{
                WhereIsYourTongue:"Où est ta langue?",
                KeepUpTheGoodWork:"Continuez comme ça!",
                RightThisInstant:"En ce moment même, enregistrez où se trouve ta langue. Cela t'aidera à suivre ton progrès au fil du temps.",
                MyTongueWasOnRoof:"Ma langue était collée au toit de ma bouche",
                MyTongueWasPushingTeeth:"Je ne sais pas ou ma langue poussait mes dents",
                ComingOutOfMeeting:"Tu viens de sortir d'une réunion ou d'un cours? Enregistre tes pensées",
                description:{
                        notificationEnabled:"Une notification sera envoyée",
                        reminder:"Nous t'enverrons une notification pour te rappeler !",
                        tellUsWhatQuietTime:"Dis-nous quand ne pas te déranger avec des notifications.",
                },
                label:{
                        clearProgress:"Efface tes données",
                        darkTheme:"Thème sombre",
                        RemindMe:"Rappelle-moi",
                        SetQuietPeriod:"Veux-tu définir une période de silence?",
                        every1Minutes:"Toutes les 1 minute",
                        every2Minutes:"Toutes les 2 minutes",
                        every15Minutes:"Toutes les 15 minutes",
                        every30Minutes:"Toutes les 30 minutes",
                        everyHour:"Toutes les heures",
                        every2Hours:"Toutes les 2 heures",
                        every4Hours:"Toutes les 4 heures",
                        every6Hours:"Toutes les 6 heures",
                        every12Hours:"Toutes les 12 heures",
                        daily:"Quotidiennement",
                        weekly:"Toute les semaines",
                        monthly:"Mensuellement",
                }
        },
        notification:{
            title: "Ta langue!",
            body: "As-tu gardé ta langue sur le toit de ta bouche?",
        },
        buttons:{
                delete:"Supprimer",
                confirm:"Confirmer",
                cancel:"Annuler",
                IHaveThoughtAboutIt:"J'y ai pensé",
                TongueWasPushingMyTeeth:"Ma langue poussait mes dents",
        },
        singleWord:{
                times:"fois",
        },
        time:{
                "12am":"00:00",
                "1am":"01:00",
                "2am":"02:00",
                "3am":"03:00",
                "4am":"04:00",
                "5am":"05:00",
                "6am":"06:00",
                "7am":"07:00",
                "8am":"08:00",
                "9am":"09:00",
                "10am":"10:00",
                "11am":"11:00",
                "12pm":"12:00",
                "1pm":"13:00",
                "2pm":"14:00",
                "3pm":"15:00",
                "4pm":"16:00",
                "5pm":"17:00",
                "6pm":"18:00",
                "7pm":"19:00",
                "8pm":"20:00",
                "9pm":"21:00",
                "10pm":"22:00",
                "11pm":"23:00",
        }
} as const
